// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCr5O3_zeLQCQTzM0pdh7gmup_7Dx_bN8',
    appId: '1:401215078651:web:adb2e406e327a53dd9f05e',
    messagingSenderId: '401215078651',
    projectId: 'flutter-course-f54c8',
    authDomain: 'flutter-course-f54c8.firebaseapp.com',
    databaseURL: 'https://flutter-course-f54c8-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-course-f54c8.appspot.com',
    measurementId: 'G-V4QG173MM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWXKsPIOrLw6e70kwkB-MAUhJMkxEyhsg',
    appId: '1:401215078651:android:38f206b59a1818b6d9f05e',
    messagingSenderId: '401215078651',
    projectId: 'flutter-course-f54c8',
    databaseURL: 'https://flutter-course-f54c8-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-course-f54c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnkvBedAp2QJK2gpFJy_B91HxH1YUv_Ag',
    appId: '1:401215078651:ios:32d4c83401197f6fd9f05e',
    messagingSenderId: '401215078651',
    projectId: 'flutter-course-f54c8',
    databaseURL: 'https://flutter-course-f54c8-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-course-f54c8.appspot.com',
    iosClientId: '401215078651-o83ofcsmr27hbblu43nt7sijpmnsqbp8.apps.googleusercontent.com',
    iosBundleId: 'com.example.stateManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnkvBedAp2QJK2gpFJy_B91HxH1YUv_Ag',
    appId: '1:401215078651:ios:32d4c83401197f6fd9f05e',
    messagingSenderId: '401215078651',
    projectId: 'flutter-course-f54c8',
    databaseURL: 'https://flutter-course-f54c8-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-course-f54c8.appspot.com',
    iosClientId: '401215078651-o83ofcsmr27hbblu43nt7sijpmnsqbp8.apps.googleusercontent.com',
    iosBundleId: 'com.example.stateManagement',
  );
}
